package com.avia.data.auth

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import com.avia.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException

/**
 * Parsed Google user credential payload extracted from AndroidX Credential Manager.
 */
data class GoogleSignInCredentials(
    val idToken: String,
    val email: String?,
    val displayName: String?,
    val avatarUri: String?
)

/**
 * Result outcome of a Google Sign-In interaction.
 */
sealed interface GoogleSignInResult {
    data class Success(val credentials: GoogleSignInCredentials) : GoogleSignInResult
    data object Cancelled : GoogleSignInResult
    data class Failure(val message: String, val cause: Throwable? = null) : GoogleSignInResult
}

/**
 * Production helper utilizing AndroidX Credential Manager and Google Identity
 * for seamless One-Tap and account selection flows in AVIA.
 */
object GoogleSignInHelper {
    private const val TAG = "GoogleSignInHelper"

    /**
     * Resolves the configured Web Client ID.
     * Looks at R.string.default_web_client_id first (auto-generated by google-services plugin when OAuth Web client exists),
     * followed by R.string.google_web_client_id.
     */
    fun resolveWebClientId(context: Context): String? {
        val defaultId = runCatching { context.getString(R.string.default_web_client_id) }.getOrNull()?.trim()
        if (!defaultId.isNullOrEmpty()) return defaultId

        val customId = runCatching { context.getString(R.string.google_web_client_id) }.getOrNull()?.trim()
        if (!customId.isNullOrEmpty()) return customId

        return null
    }

    /**
     * Triggers Google Sign-In via AndroidX Credential Manager.
     */
    suspend fun launchGoogleSignIn(context: Context): GoogleSignInResult {
        val serverClientId = resolveWebClientId(context)
        if (serverClientId.isNullOrBlank()) {
            val errorMsg = "Google Web Client ID is not configured. Please enable Google Sign-In and register SHA-1 in Firebase Console."
            Log.e(TAG, errorMsg)
            return GoogleSignInResult.Failure(errorMsg)
        }

        val credentialManager = CredentialManager.create(context)
        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(serverClientId)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        return try {
            val response = credentialManager.getCredential(context = context, request = request)
            val credential = response.credential

            when {
                credential is CustomCredential &&
                    credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL -> {
                    try {
                        val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                        GoogleSignInResult.Success(
                            GoogleSignInCredentials(
                                idToken = googleIdTokenCredential.idToken,
                                email = googleIdTokenCredential.id,
                                displayName = googleIdTokenCredential.displayName,
                                avatarUri = googleIdTokenCredential.profilePictureUri?.toString()
                            )
                        )
                    } catch (e: GoogleIdTokenParsingException) {
                        Log.e(TAG, "Failed to parse Google ID token credential", e)
                        GoogleSignInResult.Failure("Failed to extract Google ID token credential.", e)
                    }
                }
                else -> {
                    Log.w(TAG, "Unexpected credential type returned: ${credential.type}")
                    GoogleSignInResult.Failure("Unexpected credential type: ${credential.type}")
                }
            }
        } catch (e: GetCredentialCancellationException) {
            Log.i(TAG, "Google sign-in cancelled by user")
            GoogleSignInResult.Cancelled
        } catch (e: GetCredentialException) {
            Log.e(TAG, "Credential Manager request failed: ${e.message}", e)
            GoogleSignInResult.Failure(e.localizedMessage ?: "Google sign-in failed", e)
        } catch (e: Exception) {
            Log.e(TAG, "Unexpected error during Google sign-in", e)
            GoogleSignInResult.Failure(e.localizedMessage ?: "Sign-in error", e)
        }
    }
}
